### ISSUE TITLE
Firefox Desktop: Stored Sites do not sync via Firefox Sync

### ISSUE THREAD

**Issue by jmorgannz** [ttyridal/masterpassword-firefox#59] opened 2018-08-16 07:14 UTC
Title pretty well says it all.

### Fresh install of Firefox on a new PC, upon sign-in to Firefox Sync

- Masterpassword is automatically installed
- Global settings correctly reflect my settings (which are different to the defaults)
- Stored sites is **empty**, as in a fresh installation of the extension (should contain my list of stored sites)

### Change of Global Settings on PC A, manually clicking sync on PC A, and manually clicking sync on PC B

- Global settings on PC A reflect changes made (even if config page reloaded)
- Global settings on PC B **do not change** (even if config page reloaded)
- Global settings on PC A and B are now out of sync, even though manually sync'd

### Adding a stored site in PC A, then manually syncing both PC A and PC B

- Stored site shows in config page on PC A  (even if config page reloaded)
- Stored site does **not** show in config page on PC B  (even if config page reloaded)
- Stored sites on PC A and PC B are now out of sync, even though manually sync'd

**Comment by jmorgannz** [comment] 2018-08-16 07:15
According to https://wiki.mozilla.org/Services/Sync/Addon_Sync, explicit code support may be required for this to work correctly.

**Comment by ttyridal** [comment] 2018-08-16 14:57
Yes it is not implemented. This would require a change from storage.local to storage.sync

The change will also introduce ratio challenges for people with lots of sites stored (not that many actually. The chrome version uses storage.sync and typically hits the limit at about 80 sites I think it was)
Not sure what the limit is on Firefox.

The problem is first and foremost the per-record limit. (the extension stores everything in a single record). As such, a smarter way to store the sites can provide both sync and avoid the limit.

**Comment by promeneur** [comment] 2020-01-07 10:12
Hello happy new year

A suggestion : using lockwise to store masterpassword data permanently or just the time needed to sync.

Perhaps you can store data in the id and pwd fields in lockwise

Thus, masterpassword gains sync between PC FF and Android FF

**Comment by ttyridal** [comment] 2021-11-21 23:38
I'm not sure I see how Firefox lockwise would be helpful here?  
the use of `storage.sync` is implemented in the future branch and hopefully released in a not too distant future.  If enabled and user is logged in to a firefox account, site data should sync to all devices

**Comment by promeneur** [comment] 2021-11-22 09:02
Good news.

Also, there is a project at masterpassword to get a complete solution for PC and mobile devices with its own filling service to replace Samsung or other filling service if I understand well. see the new site https://spectre.app/

**Comment by promeneur** [comment] 2021-11-22 09:21
Unhappily the new spectre is not ready for Linux and Android there is only source and I can't make any java or android building.
I am not a pioneer. My smartphone and my PC are not a playground.

**Comment by ttyridal** [comment] 2021-11-23 02:02
@jmorgannz  Just a question on your last case (if you can remember, 3 years later 🙈)  When you say "manual sync" do you refer to the firefox sync feature, or copying mpsite file?

**Comment by jmorgannz** [comment] 2021-11-23 04:21
@ttyridal Manually clicking sync now (not mpsites)

**Comment by ttyridal** [comment] 2021-12-07 08:30
This has been implemented in version 2.9, now released.

Sync can be enabled in the options

**Closed as completed by ttyridal** 2021-12-07 08:30 UTC
Labels: enhancement, help wanted

**Comment by promeneur** [comment] 2021-12-07 08:47
good news, thanks
