### ISSUE TITLE
firefox plugin creates a different password than mpw or masterpassword-jui.jar 

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#64] opened 2021-02-24 15:48 UTC
Firefox plugin creates a different password than mpw or masterpassword-jui.jar for example for bz.apache.org.

It seems that ff plugin uses v1 algorithm instead of v3.

Same problem with chrome plugin.

**Comment by promeneur** [comment] 2021-02-24 16:24
The problem comes from FF plugin calculates the password with apache.org. mpw and masterpassword-gui calculates the password with bz.apache.org

**Comment by ttyridal** [comment] 2021-04-19 17:52
Hi, this plugin should be using v3 of the algorithm (v2 and v3 differs to v1 in handling characters outside us-ascii in site names and main username/password). Are you sure that's the problem?  Your example revolves around the site name. By default the plugin uses the two last parts of the site name (unless it's `.co.*`, if i remember correctly). 
You are free to change that when the dialog opens. 

That would be a duplicate of as issue #52 i think

The algorithm for selecting the default is very stupid, it should be improved to take the best match or the one used previously for the site in question, but that's another story.

**Comment by ttyridal** [comment] 2021-12-07 20:12
the site name is a user input, the addon only provides a suggestion.

**Closed as completed by ttyridal** 2021-12-07 20:12 UTC
Labels: invalid
