### ISSUE TITLE
Feature request: Remember username for each site

### ISSUE THREAD

**Issue by jamesdwilson** [ttyridal/masterpassword-firefox#38] opened 2017-02-27 22:12 UTC
When I log in, it would be nice if MP remembered the username I entered. I know this can't work on all sites, but I think in the majority of cases it is predictable.

**Comment by ttyridal** [comment] 2017-02-28 05:59
Is this a duplicate of issue #30, or is it a way to differentiate multiple users on the same site you had in mind?

**Comment by ttyridal** [comment] 2017-03-13 09:46
Close as duplicate

**Closed as completed by ttyridal** 2017-03-13 09:46 UTC
Labels: duplicate
